a2lix_translation_form:
    locales: '%app.supported_locales%'
    default_locale: '%app.default_locale%'
    templating: "@A2lixTranslationForm/bootstrap_4_layout.html.twig"
a2lix_auto_form:
    excluded_fields: [id, locale, translatable]
