sonata_admin:
    title: 'Sonata Admin'
    security:
        handler: sonata.admin.security.handler.acl

        # this service MUST implement ``Sonata\AdminBundle\Util\AdminAclUserManagerInterface``.
        acl_user_manager: App\Manager\AclUserManager

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN

        # acl security information
        information:
            STAFF:    [VIEW, EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]

        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]

        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
#    breadcrumbs:
#        # use this to change the default route used to generate the link
#        # to the parent object inside a breadcrumb, when in a child admin
#        child_admin_route: show
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            admin_commerce:
                label: ~
                icon: 'fa fa-image'
#                keep_open: true
                items: ~

##            admin_misc: ~<
            sonata_media: ~
            sonata_user: ~

    options:
        legacy_twig_text_extension: false
        lock_protection: true

    assets:
        extra_stylesheets:
            - bundles/sonatatranslation/css/sonata-translation.css
    templates:
        layout: '@SonataTranslation/standard_layout.html.twig'
    extensions:
        app.admin.extension.workflow.product:
            admins:
                - app.admin.product

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
