sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    options:
        legacy_twig_text_extension: false
    assets:
        extra_stylesheets:
            - bundles/sonatatranslation/css/sonata-translation.css
    templates:
        layout: '@SonataTranslation/standard_layout.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
