sonata_admin:
    title: 'Sonata Admin'
    security:
        handler: sonata.admin.security.handler.role

        # this service MUST implement ``Sonata\AdminBundle\Util\AdminAclUserManagerInterface``.
        acl_user_manager: App\Manager\AclUserManager

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN

        # acl security information
        information:
            OWNER: [OWNER]
            EDIT:
                - EDIT
            LIST:
                - LIST
            CREATE:
                - CREATE
            VIEW:
                - VIEW
            DELETE:
                - DELETE
            EXPORT:
                - EXPORT
            ALL:
                - ALL

#            STAFF:    [VIEW, LIST, CREATE, EDIT ]
#            EDITOR:   [OPERATOR, EXPORT, OWNER]
#            ADMIN:    [MASTER]
#        staff_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]

        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
    breadcrumbs:
        # use this to change the default route used to generate the link
        # to the parent object inside a breadcrumb, when in a child admin
        child_admin_route: show
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
#            - { type: user_block, roles: [ROLE_USER]}
        groups:
#            id:
#                label: ~
#                label_catalogue: ~
#                icon: ~
#                provider: ~
#                items:
#                    admin: ~
#                    label: ~
#                    route: ~
#                    route_params: ~
#                item_adds: []
#                roles: []
            admin_commerce:
                label: ~
                icon: 'fa fa-image'
                keep_open: true
                items:
                    - app.admin.product
                    - app.admin.category

##            admin_misc: ~<
            sonata_media: ~
            sonata_user: ~

    options:
        legacy_twig_text_extension: false
        lock_protection: true

    assets:
        extra_stylesheets:
            - build/app.css
            - bundles/sonatatranslation/css/sonata-translation.css
    templates:
        layout: 'Admin/standard_layout.html.twig'
    extensions:
        app.admin.extension.workflow.editorial:
            admins:
                - app.admin.product
