sonata_admin:
    assets:
        extra_stylesheets:
            - bundles/sonatatranslation/css/sonata-translation.css

sonata_block:
    blocks:
        sonata_translation.block.locale_switcher: null

sonata_translation:
    locales: '%app.supported_locales%'
    default_locale: '%app.default_locale%'
    locale_switcher: true
        # change default behavior for translated field filtering.
    default_filter_mode: knplabs
    # here enable the types you need
    knplabs:
        enabled: true
    #phpcr:
    #    enabled: true
