admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    locale: vn|en|ru
    requirements:
        _locale: vn|en|ru
        _format: html|xml