#index:
#    path: /
#    controller: App\Controller\DefaultController::index

sonata_translation:
  resource: '@SonataTranslationBundle/Resources/config/routes.yaml'

gallery:
  resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
  prefix: /media/gallery

media:
  resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
  prefix: /media
